# Generated by Django 5.2.13 on 2026-05-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='whatsapp_activo',
            field=models.BooleanField(default=False, help_text='Plan Premium: habilita el envío de notificaciones por WhatsApp.'),
        ),
    ]
