# Generated by Django 5.2.13 on 2026-04-30 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono_whatsapp', models.CharField(max_length=15)),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor'), ('APODERADO', 'Apoderado')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='GradoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], max_length=10)),
                ('grado', models.PositiveSmallIntegerField()),
                ('nombre_seccion', models.CharField(max_length=60)),
                ('año_academico', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Grado y Sección',
                'verbose_name_plural': 'Grados y Secciones',
                'unique_together': {('grado', 'nombre_seccion', 'año_academico')},
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(editable=False, max_length=20, unique=True)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumnos/fotos/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='colegios.apoderado')),
                ('grado_seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='colegios.gradoseccion')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
    ]
