# Generated by Django 5.2.13 on 2026-07-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0002_codigo_solo_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
