# Generated by Django 5.2.13 on 2026-04-30 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_entrada', models.TimeField()),
                ('hora_limite_puntual', models.TimeField(help_text='Hasta esta hora se marca Presente')),
                ('hora_cierre', models.TimeField(help_text='A esta hora se cierran ausentes y se envían WhatsApp')),
                ('dias_laborables', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Horario Escolar',
                'verbose_name_plural': 'Horarios Escolares',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_registro', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDANZA', 'Tardanza'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado')], max_length=12)),
                ('metodo', models.CharField(choices=[('ESCANER', 'Escáner'), ('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='ESCANER', max_length=10)),
                ('estado_original', models.CharField(blank=True, choices=[('PRESENTE', 'Presente'), ('TARDANZA', 'Tardanza'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado')], max_length=12, null=True)),
                ('modificado_en', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('whatsapp_enviado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='colegios.alumno')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_modificadas', to='usuarios.usuariosistema')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to='usuarios.usuariosistema')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'alumno__apellido_paterno'],
            },
        ),
        migrations.CreateModel(
            name='ContadorJustificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contador_justificaciones', to='colegios.alumno')),
            ],
            options={
                'verbose_name': 'Contador de Justificaciones',
                'verbose_name_plural': 'Contadores de Justificaciones',
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asistencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificacion', to='asistencia.asistencia')),
                ('justificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_emitidas', to='usuarios.usuariosistema')),
            ],
            options={
                'verbose_name': 'Justificación',
                'verbose_name_plural': 'Justificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO_MANUAL', 'Ingreso manual detectado'), ('LIMITE_JUSTIF', 'Límite de justificaciones'), ('GENERAL', 'General')], max_length=20)),
                ('mensaje', models.TextField()),
                ('rol_destino', models.CharField(max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('leida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_leidas', to='usuarios.usuariosistema')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='SesionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=10)),
                ('hora_apertura_real', models.TimeField(blank=True, null=True)),
                ('hora_cierre_real', models.TimeField(blank=True, null=True)),
                ('total_alumnos', models.PositiveIntegerField(default=0)),
                ('total_presentes', models.PositiveIntegerField(default=0)),
                ('total_tardanzas', models.PositiveIntegerField(default=0)),
                ('total_ausentes', models.PositiveIntegerField(default=0)),
                ('total_justificados', models.PositiveIntegerField(default=0)),
                ('whatsapp_enviados', models.BooleanField(default=False)),
                ('abierta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_abiertas', to='usuarios.usuariosistema')),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_cerradas', to='usuarios.usuariosistema')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencia.horarioescolar')),
            ],
            options={
                'verbose_name': 'Sesión Diaria',
                'verbose_name_plural': 'Sesiones Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='asistencia.sesiondiaria'),
        ),
        migrations.CreateModel(
            name='IngresoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('alerta_enviada', models.BooleanField(default=False)),
                ('ultimo_intento', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_manuales', to='colegios.alumno')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_manuales', to='asistencia.sesiondiaria')),
            ],
            options={
                'verbose_name': 'Ingreso Manual',
                'verbose_name_plural': 'Ingresos Manuales',
                'unique_together': {('sesion', 'alumno')},
            },
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha', 'estado'], name='asistencia__fecha_0faabf_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['alumno', 'fecha'], name='asistencia__alumno__86797f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno', 'fecha')},
        ),
    ]
